import pandas as pd
import csv
k=[]
print("The Bash")
print("********")
print("The BASH  is an event management company which looks into providing high quality and professional services for wedding ,  coorporate events and many more. Whether you wish small or large or an exotic event, we will make your event special and memorable. We welcome you to The Bash family")
print()
print("We guarantee you that our services can successfully meet your demands at any scale. We provide guidance on the best options for you, handle logistics within timelines, manage budgets, ensure safety and professionally driver results each time")
print("All are ready to do whatever it takes to make your special days even more special!!!")
print("1.Our Service")
print("2.Bookings")
print("3.Cancellation")
print("4.Summary of the bookings")
x=input("Looking for More Details?(y/n):")
while x=="Y" or x=="y":
  print("1.Our Service")
  print("2.Bookings")
  print("3.Cancellation")
  print("4.Summary of the bookings")
  a=int(input("Enter an option:"))
  if a==1:
    print("Our Services")
    print("*******")
    print("1.Package1:Rs.30,oo,000")
    print("Inclusive of all taxes, the rent of the venue for 2 days is included in 30,00,000. Additional charges may apply foe each 10 hrs,20% of theb total amount would be deducted as Commission for the management and the rest will be used for the arrangements.")
    print()
    print("*Venue selection (Destination, hotels(5star),hall),Beauty at its best,Live entertainment(By the top artist),Hospitality, Invitation Cards,Florists ,Picture perfect(Inclusive of Photoshoot),Gift,Bookings(5star,3star),Travel and more,Bachelor Parties,Ghori,Food and Beverages,Doli,Decorations")
    print()
    print("1.2)Package2:Rs.14,00,000")
    print("(1400000 is inclusive of the rent for the venue upto one-and-a-half-day and tax.Excluding food,Additional charges may apply for the each 10 hrs after the alloted time)")
    print()
    print("*Venue Selection(hall,hotel), Florists,Picture perfect(Exclusive of photoshoot-rs---),Invitation card,bookings(3star,2star),Food And Beverages,Gift,Beauty at its best,Music,Decorations")
    print("1.3)Package3:Rs.5,open")
    print("(500000 is inclusive of the rent for the venue upto one-and-a-half-day and tax.Excluding food,Additional charges may apply for the next 10 hrs)")
    print()
    print("*Venue selection(hall),florists(*Simple*),Picture perfect(exclusive of photoshoot),Decorations (Simple),  Food(Excluding Beverages),Beauty at its best")
    print()
    print("2.CORPORATE EVENT MANAGEMENT")
    print()
    print("2.1)Package1:Rs.60,000")
    print("((For 3  hours and it is inclusive of tax.Additionl charges my apply for each hour,inclusive of food food for 20 plates.)")
    print()
    print("*Event conceptualization,Design and Decoe, Sound, Light and AV,Event flow, Entertainment programing, Hospitality ,Videography and photohgraphy")
    print("Branded apperal will be provided as an complimentary gift to all the participants.")
    print()
    print("2.2)Package2:Rs.30,000")
    print("(Rent for 2 hours is inclusive in the package and also the Tax.Additional charges may apply for each hour)")
    print()
    print("Event conceptualization, Design and decor, Sound, light and AV, Event flow,Photography")
    print()
    print("3.Other Services")
    print("******************")
    print("3.1)Product Launch")
    print()
    print("Have  you got a new product that you are looking to introduce into the marketplace? Well, if that is the case, then you are going to need the proper product launch party set into place. Each and every product have their own value and needs, before market to aware from new product to the general customer and dealers. We plan unique and different idea for the product launch with the new marketing stratergy with the help of entertainment show and  publicity (Print, electronic, FM, signage, hoardings etc..")
    print("We plan and execute high impact product launches. An effective product launch can make a huge impact on whether a product succeedes or  fails in the marketplace. We give your product the best chance of success by positioning your at the right place against your competitors and creating buzz with the customers and the industry.")
    print("The fixed cost is Rs2,00,000")
    print("(Additional charges may apply for 1 hour and it is inclusive of the tax.Commision for the management will be 20% from the total tickets sold to the public)")
    print()
    print("2.Merchandise for Wedding(only)")
    print("*Gifts for friends and family")
    print("#Packaging")
    print("Customised concepts to make your keepsakes ever more memorable. From boxes lined in silk to vintage lace bags, we do it all based on our customer's wish and budget!")
    print()
    print("(2% and 20% of the budget fixed by customer will be deducted for the Tax and Commision for the Event management.)")
    print()
    print("4.Theme Parties")
    print("We take an essential care of giving your event a special touch and to make it memorable. We love giving themes to all your parties, be it a Grand Birthday Celebration, Wedding Anniversaries, Bridal Shower or any special occasion. We have the ability to transform a normal venue to the heavenly gardens of Vrindavan or the surreal canals of Venice. A theme transforms the entire aura of the event.")
    print("(2% Tax  and 20% Commmision from the fund will be deductedand rest will used for the arragements)")
  elif a==2:
    print("1.Wedding Planners(Decors)")
    print("2.Corporate Event Management")
    print("3.Others")
    b=int(input("Enter an option:"))
    if b==1:
      print("1.Package1:Rs.30,00,000")
      print("2.Package2:Rs,14,00,000")
      print("3.Package3:6,00,000")
      p=(input("Enter the package you want to go with:"))
      if p=="Package1" or p=="package1" or p==1:
        cust=(input("Enter your name:"))
        ph=float(input("Enter your Contact Number:"))
        email=input("Enter your email id:")
        guest=int(input("Enter the no.of guests:"))
        i_d=float(input("Please enter first  last 4 digits of your mobile number(This will be your I_D):"))
        k.append(i_d)
        df={"CustomerI_D":[i_d],"CustomerName":[cust],"PhoneNumber":[ph],"Email_ID":[email],"No.of Guests":[guest]}
        tax1=60,000
        comm1=6,00,000
        plate=2000
        price=int(input("enter the no.of plates you want for the guests"))
        exp=price*plate
        print("Invoice:")
        print("Tax:60,000")
        print("Commission:6,00,000")
        print("Preperation Expenses:23,40,000")
        print("Food and Beverages:",exp)
        print()
        print("The Grand Total:Rs.",3000000+exp)
                   
        print()
        print("*If you cancel your booking with 24 -0 hrs then you will be fully refunded.")
        print("*If you cancel your bookings within 448hrs to 24hrs then 50% of the total amount will be refunded")
        print("If the Cancelation exceedes 7 days to 48 hrs, refund will not be done")
        c=input("Ready to Book(y/n):")
        if c=="Y" or c=="y":
          print("Welcome to The Bash Family!")
          print("For further discussions and details kindy Contact the below mentiones Number:")
          print("Emp1:+91 97452XXXXX")
          print("OR")
          print("Emp2:+91 96543xxxxx")
        elif c=="N" or c=="n":
          print("Thank You for Visitng,Hope to Meet you soon!")
      elif p=="Package2" or p=="package2" or p==2:
        cust1=(input("Enter your name:"))
        ph1=float(input("Enter your Contact Number:"))
        email1=input("Enter your email id:")
        nop1=int(input("Enter the no.of guests"))
        i_d1=int(input("Please last  4 digits of your mobile number(This will be your I_D)"))
        df1={"CustomerI_D":[i_d1],"CustomerName":[cust1],"PhoneNumber":[ph1],"Email_ID":[email1],"No.of Guests":[nop1]}
        k.append(i_d1)
        plate1=1000
        price1=int(input("enter the no.of plates you want for the guests"))
        exp1=nop1*price1
        print("Invoice:")
        print("Tax:28000")
        print("Commission:2,80,000")
        print("Preperation Expenses:10,92,000")
        print("Food and Beverages:",exp1)
        print()
        print("The Grand Total:",1400000+exp1)
       
        print("*If you cancel your booking with 24 -0 hrs then you will be fully refunded.")
        print("*If you cancel your bookings within 448hrs to 24hrs then 50% of the total amount will be refunded")
        print("If the Cancelation exceedes 7 days to 48 hrs, refund will not be done")
        c1=input("Ready to Book(y/n):")
        if c1=="Y" or c1=="y":
          print("Welcome to The Bash Family!")
          print("For further discussions and details kindy Contact the below mentiones Number:")
          print("Emp1:+91 97452XXXXX")
          print("OR")
          print("Emp2:+91 96543xxxxx")
        elif c1=="N" or c1=="n":
          print("Thank You for Visitng,Hope to Meet you soon!")
      elif p=="Package3" or p=="package3":
        cust2=(input("Enter your name:"))
        ph2=float(input("Enter your Contact Number:"))
        email2=input("Enter your email id:")
        nop2=int(input("Enter the no.of guests:"))
        i_d2=float(input("Please enter  last 4 digits of your mobile number(This will be your I_D):"))
        df2={"CustomerI_D":[i_d2],"CustomerName":[cust2],"PhoneNumber":[ph2],"Email_ID":[email2],"No.of guests":[nop2]}
        k.insert(0,i_d2)
        plate2=500
        price2=int(input("Enter the no.of plates you want for the guests"))
        exp2=plate2*price2
        print("Invoice:")
        print("Tax:3,000")
        print("Commission:30,000")
        print("Preperation Expenses:5,67,000")
        print("Food and Beverages:",exp2)
        print()
        print("The Grand Total:",600000+exp2)
        print("*If you cancel your booking with 24 -0 hrs then you will be fully refunded.")
        print("*If you cancel your bookings within 448hrs to 24hrs then 50% of the total amount will be refunded")
        print("If the Cancelation exceedes 7 days to 48 hrs, refund will not be done")
        c=input("Ready to Book(y/n):")
        c2=input("Ready to Book(y/n):")
        if c2=="Y" or c2=="y":
          print("Welcome to The Bash Family!")
          print("For further discussions and details kindy Contact the below mentiones Number:")
          print("Emp1:+91 97452XXXXX")
          print("OR")
          print("Emp2:+91 96543xxxxx")
        elif c2=="N" or c2=="n":
          print("Thank You for Visitng,Hope to Meet you soon!")
    elif b==2:
      print("1.Package1:Rs.60,000")
      print("2.Package2:30,000")
      p1=input("Enter the name of the package you want to fo with:")
      if p1=="package1" or p1=="Pacakge1" or p1==1:
        comp=input("Enter the Comapy Name:")
        cust3=(input("Enter your name:"))
        ph3=float(input("Enter your Contact Number:"))
        email3=input("Enter your email id:")
        nop3=int(input("Enter the no.of guests:"))
        i_d3=float(input("Please enter last 4 digits of your mobile number(This will be your I_D):"))
        df3={"CustomerI_D":[i_d3],"Comany Name":[comp],"CustomerName":[cust3],"PhoneNumber":[ph3],"Email_ID":[email3],"No.of guests":[nop3]}
        k.insert(0,i_d3)
        plate3=200
        print("The price of one Plate:",plate3)
        platep3=int(input("Enter the no.of plates you want for all your guests:"))
        exp3=platep3*nop3
        print("Invoive:")
        print("Tax:Rs.300")
        print("Commission:3000")
        print("Food and Beverages:",exp3)
        print("Preperation expenses:5,67,000")
        print("The Grand Total:",60000+exp3)
        print("*If you cancel your booking with 24 -0 hrs then you will be fully refunded.")
        print("*If you cancel your bookings within 448hrs to 24hrs then 50% of the total amount will be refunded")
        print("If the Cancelation exceedes 7 days to 48 hrs, refund will not be done")
        c3=input("Ready to Book(y/n):")
        if c3=="Y" or c3=="y":
          print("Welcome to The Bash Family!")
          print("For further discussions and details kindy Contact the below mentiones Number:")
          print("Emp1:+91 97452XXXXX")
          print("OR")
          print("Emp2:+91 96543xxxxx")
        elif c3=="N" or c3=="n":
          print("Thank You for Visitng,Hope to Meet you soon!")
      if p1=="package2" or p1=="Pacakge2":
        comp1=input("Enter the Comapy Name:")
        cust4=(input("Enter your name:"))
        ph4=float(input("Enter your Contact Number:"))
        email4=input("Enter your email id:")
        nop4=int(input("Enter the no.of guests:"))
        i_d4=eval(input("Please enter first four letters of your name followed by last 4 digits of your mobile number(This will be your I_D):"))
        k.insert(0,i_d4)
        df4={"CustomerI_D":[i_d4],"Comany Name":[comp1],"CustomerName":[cust4],"PhoneNumber":[ph4],"Email_ID":[email4],"No.of guests":[nop4]}
        plate4=100
        print("The price of one Plate:",plate4)
        platep1=int(input("Enter the no.of plates you want for all your guests:"))
        exp4=plate1*platep1
        print("Invoive:")
        print("Tax:Rs.600")
        print("Commission:6000")
        print("Food and Beverages:",exp4)
        print("Preperation expenses:23,400")
        print("The Grand Total:",30000+exp4)
        print("*If you cancel your booking with 24 -0 hrs then you will be fully refunded.")
        print("*If you cancel your bookings within 448hrs to 24hrs then 50% of the total amount will be refunded")
        print("If the Cancelation exceedes 7 days to 48 hrs, refund will not be done")
        c3=input("Ready to Book(y/n):")
        if c3=="Y" or c3=="y":
          print("Welcome to The Bash Family!")
          print("For further discussions and details kindy Contact the below mentiones Number:")
          print("Emp1:+91 97452XXXXX")
          print("OR")
          print("Emp2:+91 96543xxxxx")
        elif c3=="N" or c3=="n":
          print("Thank You for Visitng,Hope to Meet you soon!")
    elif b==3:
      print("1.Product Launch")
      print("2.Merchandise for Wedding(Only)")
      print("3.Theme Parties")
      p1=int(input("Enter an Option:"))
      if p1==1:
        print("Product Launch")
        comp2=input("Enter the Comapy Name:")
        cust5=(input("Enter your name:"))
        ph5=float(input("Enter your Contact Number:"))
        email5=input("Enter your email id:")
        nop5=int(input("Enter the no.of guests:"))
        i_d5=eval(input("Please enter first four letters of your name followed by last 4 digits of your mobile number(This will be your I_D):"))
        df5={"CustomerI_D":[i_d4],"Comany Name":[comp2],"CustomerName":[cust5],"PhoneNumber":[ph5],"Email_ID":[5],"No.of guests":[nop8]}
        k.insert(0,i_d5)
        plate5=200
        print("The price of one Plate:",plate)
        platep5=int(input("Enter the no.of plates you want for all your guests:"))
        exp5=plate5*platep5
        print("Invoive:")
        print("Tax:Rs.4000")
        print("Commission:40000")
        print("Food and Beverages:",exp5)
        print("Preperation expenses:1,56,000")
        print("The Grand Total:",200000+exp5)
        print("*If you cancel your booking with 24 -0 hrs then you will be fully refunded.")
        print("*If you cancel your bookings within 448hrs to 24hrs then 50% of the total amount will be refunded")
        print("If the Cancelation exceedes 7 days to 48 hrs, refund will not be done")
        c4=input("Ready to Book(y/n):")
        if c4=="Y" or c4=="y":
          print("Welcome to The Bash Family!")
          print("For further discussions and details kindy Contact the below mentiones Number:")
          print("Emp1:+91 97452XXXXX")
          print("OR")
          print("Emp2:+91 96543xxxxx")
        elif c4=="N" or c4=="n":
          print("Thank You for Visitng,Hope to Meet you soon!")
      if p1==2:
        print("Merchandise For Weddings(Only)")
        comp3=input("Enter the Comapy Name:")
        cust6=(input("Enter your name:"))
        ph6=float(input("Enter your Contact Number:"))
        email6=input("Enter your email id:")
        nop6=int(input("Enter the no.of guests:"))
        i_d6=eval(input("Please enter first four letters of your name followed by last 4 digits of your mobile number(This will be your I_D):"))
        df6={"CustomerI_D":[i_d5],"Comany Name":[comp3],"CustomerName":[cust6],"PhoneNumber":[ph6],"Email_ID":[email6],"No.of guests":[nop6]}
        k.insert(0,i_d6)
        print("Kindly Note")
        print("************")
        print("2% and 20% of the budget given by you would be cut off as tax and the remmaining amount will onlly be used for buying  gift and the no.of guest will also reflect the price of one gift.")
        budget=float(input("Enter Your Budget"))
        gift=float(input("Enter the no.of  gifts You would like to Distribute"))
        print()
        tax4=(budget*2/100)
        comm4=(budget*20/100)
        prepexp=budget-(tax4+comm4)
        print("Invoive:")
        print("Tax:Rs.",tax4)
        print("Coomission:Rs",comm4)
        print("Price of the gift:Rs.",prepexp)
        print("Grand Total:Rs.",budget)
        print("*If you cancel your booking with 24 -0 hrs then you will be fully refunded.")
        print("*If you cancel your bookings within 448hrs to 24hrs then 50% of the total amount will be refunded")
        print("If the Cancelation exceedes 7 days to 48 hrs, refund will not be done")
        c5=input("Ready to Book?(y/n):")
        if c5=="Y" or c5=="y":
          print("Welcome to The Bash Family!")
          print("For further discussions and details kindy Contact the below mentiones Number:")
          print("Emp1:+91 97452XXXXX")
          print("OR")
          print("Emp2:+91 96543xxxxx")
        elif c5=="N" or c5=="n":
          print("Thank You for Visitng,Hope to Meet you soon!")
  elif a==3:
    print("Cancelation")
    cancel=float(input("Enter your Customer i_d:"))
    if cancel in k:
      c1=input(("Are you sure that you want to cancle?(y/n):"))
      if c1=="Y" or c1=="y":
        k.remove(cancel)
        print("The Bookings has been canceled,Hope to meet you soon!")
      else:
        print("Sorry,No bookings have been made with such an I_D")
  x=input("Do you want to continue?(y/n):")
  if x=="n" or x=="N":
    exit()